name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - json5
  - jupyter_client
  - jupyter_core
  - jupyter_server
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - notebook
  - uvicorn
  - fastapi
  - pip:
    - boto3
    - botocore
    - gitpython==3.1.26
    - ipykernel==6.6.0
    - ipython==7.30.1
    - numpy
    - cachetools
    - pymilvus==1.1.1
    - python-arango==7.2.0
    - opencv-python
    - opencv-contrib-python
    - nebula3_database==0.2.2
