# Gradient Workflow Tutorial
#
# This is the YAML file used to run the Gradient modeling Workflow for the sample project based on StyleGAN2 at
# https://docs.paperspace.com.
#
#
# Last updated: Dec 07 2021
#
# Trigger Workflow to run on any update (commit) to the repository when linked to a Gradient project
# (uncomment to activate)

defaults:
  env:
    PIPELINE_ID: "12345678"

jobs:
    
  # 1. Clone StyleGAN repo into managed storage provider dataset

  cloneVisualCluesRepo:
    resources:
      instance-type: C4
    outputs:
      repo:
        type: volume
    with:
      url: https://github.com/NEBULA3PR0JECT/visual_clues.git


  # 2. running jobs

  printEnv1:
    resources:
      instance-type: C4
    needs:
      - cloneVisualCluesRepo
    inputs:
      repo: cloneVisualCluesRepo.outputs.repo
    uses: script@v1
    with:
      script: |-
        cp -R /inputs/repo /visual_clues
        cd /visual_clues
        pip install -r requirements.txt
        pip install nebula3_experts==1.2.1
        python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'
        python run_sprint4.py
      image: python:3

