# Gradient Workflow Tutorial
#
# This is the YAML file used to run the Gradient modeling Workflow for the sample project based on StyleGAN2 at
# https://docs.paperspace.com.
#
#
# Last updated: Dec 07 2021
#
# Trigger Workflow to run on any update (commit) to the repository when linked to a Gradient project
# (uncomment to activate)

defaults:
  env:
    PIPELINE_ID: "12345678"

jobs:
    
  # 1. Clone StyleGAN repo into managed storage provider dataset

  cloneVisualCluesRepo:
    resources:
      instance-type: A6000
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/NEBULA3PR0JECT/visual_clues.git

  # 2. running jobs

  printEnv1:
    resources:
      instance-type: A6000
    needs:
      - cloneVisualCluesRepo
    inputs:
      repo: cloneVisualCluesRepo.outputs.repo
    uses: script@v1
    with:
      script: |-
        cp -R /inputs/repo /visual_clues
        cd /visual_clues
        pip install --index-url http://74.82.29.209:8090 nebula3_experts==1.2.2 --trusted-host 74.82.29.209
        pip install -r requirements.txt
        python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'
        python run_sprint4.py
      image: aharonamir/nebula3_experts:base_gpu

